package com.hpeu.sparkStreaming.beans;

import java.io.Serializable;
import java.util.UUID;

/**
 * Created by Administrator on 2018/4/1/001.
 * The format of the signals generated by devices
 */
public class DeviceSignal implements Serializable{
    private String devType;
    private String devID;
    private Long timestamp;
    private String signal;

    public String getDevType() {
        return devType;
    }

    public void setDevType(String devType) {
        this.devType = devType;
    }

    public String getDevID() {
        return devID;
    }

    public void setDevID(String devID) {
        this.devID = devID;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public String getSignal() {
        return signal;
    }

    public void setSignal(String signal) {
        this.signal = signal;
    }

    @Override
    public String toString() {
        return "DeviceSignal{" +
                "devType='" + devType + '\'' +
                ", devID='" + devID + '\'' +
                ", timestamp=" + timestamp +
                ", signal='" + signal + '\'' +
                '}';
    }
}
